"""add trip fields

Revision ID: 260e2170c60b
Revises: a830054fd178
Create Date: 2026-08-01 17:01:02.684002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '260e2170c60b'
down_revision: Union[str, Sequence[str], None] = 'a830054fd178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('start_location', sa.String(), nullable=False))
    op.add_column('trips', sa.Column('end_location', sa.String(), nullable=False))
    op.add_column('trips', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('trips', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.add_column('trips', sa.Column('status', sa.String(), nullable=True))
    op.alter_column('trips', 'vehicle_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('trips', 'driver_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('trips', 'shipment_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'shipment_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('trips', 'driver_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('trips', 'vehicle_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('trips', 'status')
    op.drop_column('trips', 'end_time')
    op.drop_column('trips', 'start_time')
    op.drop_column('trips', 'end_location')
    op.drop_column('trips', 'start_location')
    # ### end Alembic commands ###
