"""add fuel record fields

Revision ID: 2b489bc76240
Revises: dfe90f177b8f
Create Date: 2026-08-01 18:20:17.988926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b489bc76240'
down_revision: Union[str, Sequence[str], None] = 'dfe90f177b8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_records', sa.Column('fuel_amount', sa.Float(), nullable=False))
    op.add_column('fuel_records', sa.Column('fuel_cost', sa.Float(), nullable=False))
    op.add_column('fuel_records', sa.Column('fuel_station', sa.String(), nullable=False))
    op.add_column('fuel_records', sa.Column('filled_by', sa.String(), nullable=True))
    op.add_column('fuel_records', sa.Column('fuel_date', sa.DateTime(), nullable=True))
    op.alter_column('fuel_records', 'vehicle_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fuel_records', 'vehicle_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('fuel_records', 'fuel_date')
    op.drop_column('fuel_records', 'filled_by')
    op.drop_column('fuel_records', 'fuel_station')
    op.drop_column('fuel_records', 'fuel_cost')
    op.drop_column('fuel_records', 'fuel_amount')
    # ### end Alembic commands ###
