"""add notification fields

Revision ID: 4379fe1333c6
Revises: f1f98b5c50df
Create Date: 2026-07-31 20:16:07.022022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4379fe1333c6'
down_revision: Union[str, Sequence[str], None] = 'f1f98b5c50df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('title', sa.String(), nullable=False))
    op.add_column('notifications', sa.Column('message', sa.String(), nullable=False))
    op.add_column('notifications', sa.Column('is_read', sa.Boolean(), nullable=True))
    op.add_column('notifications', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'created_at')
    op.drop_column('notifications', 'is_read')
    op.drop_column('notifications', 'message')
    op.drop_column('notifications', 'title')
    # ### end Alembic commands ###
