"""add driver fields

Revision ID: 8780a39ff652
Revises: f6a5f5a91350
Create Date: 2026-08-01 18:52:28.289627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8780a39ff652'
down_revision: Union[str, Sequence[str], None] = 'f6a5f5a91350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('name', sa.String(), nullable=False))
    op.add_column('drivers', sa.Column('phone', sa.String(), nullable=False))
    op.add_column('drivers', sa.Column('license_number', sa.String(), nullable=False))
    op.add_column('drivers', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'status')
    op.drop_column('drivers', 'license_number')
    op.drop_column('drivers', 'phone')
    op.drop_column('drivers', 'name')
    # ### end Alembic commands ###
