"""add vehicle fields

Revision ID: b1a802c4eaa4
Revises: b284c1ee78ce
Create Date: 2026-08-01 16:34:37.772022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1a802c4eaa4'
down_revision: Union[str, Sequence[str], None] = 'b284c1ee78ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('registration_number', sa.String(), nullable=False))
    op.add_column('vehicles', sa.Column('vehicle_type', sa.String(), nullable=False))
    op.add_column('vehicles', sa.Column('capacity', sa.String(), nullable=False))
    op.add_column('vehicles', sa.Column('fuel_type', sa.String(), nullable=False))
    op.add_column('vehicles', sa.Column('status', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'vehicles', ['registration_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='unique')
    op.drop_column('vehicles', 'created_at')
    op.drop_column('vehicles', 'status')
    op.drop_column('vehicles', 'fuel_type')
    op.drop_column('vehicles', 'capacity')
    op.drop_column('vehicles', 'vehicle_type')
    op.drop_column('vehicles', 'registration_number')
    # ### end Alembic commands ###
