"""add gps tracking fields

Revision ID: b284c1ee78ce
Revises: e709c1cca3af
Create Date: 2026-07-31 21:49:25.938736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b284c1ee78ce'
down_revision: Union[str, Sequence[str], None] = 'e709c1cca3af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gps_tracking', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('gps_tracking', sa.Column('longitude', sa.Float(), nullable=False))
    op.add_column('gps_tracking', sa.Column('speed', sa.Float(), nullable=True))
    op.add_column('gps_tracking', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.alter_column('gps_tracking', 'vehicle_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gps_tracking', 'vehicle_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('gps_tracking', 'timestamp')
    op.drop_column('gps_tracking', 'speed')
    op.drop_column('gps_tracking', 'longitude')
    op.drop_column('gps_tracking', 'latitude')
    # ### end Alembic commands ###
