"""add maintenance fields

Revision ID: dfe90f177b8f
Revises: 22c3c95adee2
Create Date: 2026-08-01 18:11:58.731948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfe90f177b8f'
down_revision: Union[str, Sequence[str], None] = '22c3c95adee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_maintenance', sa.Column('service_type', sa.String(), nullable=False))
    op.add_column('vehicle_maintenance', sa.Column('description', sa.String(), nullable=True))
    op.add_column('vehicle_maintenance', sa.Column('service_date', sa.DateTime(), nullable=True))
    op.add_column('vehicle_maintenance', sa.Column('next_service_date', sa.DateTime(), nullable=True))
    op.add_column('vehicle_maintenance', sa.Column('cost', sa.Float(), nullable=True))
    op.add_column('vehicle_maintenance', sa.Column('status', sa.String(), nullable=True))
    op.alter_column('vehicle_maintenance', 'vehicle_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle_maintenance', 'vehicle_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('vehicle_maintenance', 'status')
    op.drop_column('vehicle_maintenance', 'cost')
    op.drop_column('vehicle_maintenance', 'next_service_date')
    op.drop_column('vehicle_maintenance', 'service_date')
    op.drop_column('vehicle_maintenance', 'description')
    op.drop_column('vehicle_maintenance', 'service_type')
    # ### end Alembic commands ###
