"""add shipment fields

Revision ID: e709c1cca3af
Revises: 4379fe1333c6
Create Date: 2026-07-31 21:24:11.872719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e709c1cca3af'
down_revision: Union[str, Sequence[str], None] = '4379fe1333c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('tracking_number', sa.String(), nullable=False))
    op.add_column('shipments', sa.Column('source', sa.String(), nullable=False))
    op.add_column('shipments', sa.Column('destination', sa.String(), nullable=False))
    op.add_column('shipments', sa.Column('status', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('eta', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'shipments', ['tracking_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipments', type_='unique')
    op.drop_column('shipments', 'created_at')
    op.drop_column('shipments', 'eta')
    op.drop_column('shipments', 'status')
    op.drop_column('shipments', 'destination')
    op.drop_column('shipments', 'source')
    op.drop_column('shipments', 'tracking_number')
    # ### end Alembic commands ###
