"""add attendance fields

Revision ID: f6a5f5a91350
Revises: 2ecbbdd5b4c7
Create Date: 2026-08-01 18:31:32.601789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6a5f5a91350'
down_revision: Union[str, Sequence[str], None] = '2ecbbdd5b4c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('check_in', sa.DateTime(), nullable=True))
    op.add_column('attendance', sa.Column('check_out', sa.DateTime(), nullable=True))
    op.add_column('attendance', sa.Column('status', sa.String(), nullable=False))
    op.alter_column('attendance', 'driver_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'driver_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('attendance', 'status')
    op.drop_column('attendance', 'check_out')
    op.drop_column('attendance', 'check_in')
    # ### end Alembic commands ###
