import { useEffect, useMemo, useState } from "react";
import api from "../api/axios";

const active = (status) => status?.trim().toLowerCase() === "in progress";
export default function Attendance() {
  const [records, setRecords] = useState([]); const [drivers, setDrivers] = useState([]); const [trips, setTrips] = useState([]); const [form, setForm] = useState({ driver_id: "", check_in: "", check_out: "", status: "Present" }); const [editingId, setEditingId] = useState(null); const [error, setError] = useState("");
  const load = async () => { try { const [attendance, driverData, tripData] = await Promise.all([api.get("/attendance/"), api.get("/drivers/"), api.get("/trips/")]); setRecords(attendance.data); setDrivers(driverData.data); setTrips(tripData.data); } catch (e) { setError(e.response?.data?.detail || "Unable to load attendance."); } };
  useEffect(() => { void load(); }, []);
  const activeTrips = useMemo(() => trips.filter((trip) => active(trip.status)), [trips]); const driverName = (id) => drivers.find((driver) => String(driver.driver_id) === String(id))?.name || "Unknown driver"; const vehicleFor = (id) => { const trip = activeTrips.find((item) => String(item.driver_id) === String(id)); return trip?.vehicle_id || "No active trip"; };
  const save = async (event) => { event.preventDefault(); try { const payload = { ...form, check_in: new Date(form.check_in).toISOString(), check_out: form.check_out ? new Date(form.check_out).toISOString() : null }; if (editingId) await api.put(`/attendance/${editingId}`, payload); else await api.post("/attendance/", payload); setForm({ driver_id: "", check_in: "", check_out: "", status: "Present" }); setEditingId(null); await load(); } catch (e) { setError(e.response?.data?.detail || "Unable to save attendance."); } };
  const visible = records;
  return <div className="p-8 bg-gray-100 min-h-screen"><h1 className="text-4xl font-bold mb-2">Driver Attendance</h1><p className="text-gray-600 mb-6">Mark Present, Absent, or Leave for any registered driver.</p>{error && <div className="mb-4 p-3 rounded bg-red-50 text-red-700">{error}</div>}<form onSubmit={save} className="bg-white rounded-xl shadow p-6 grid md:grid-cols-2 gap-4"><select required value={form.driver_id} onChange={(e) => setForm({ ...form, driver_id: e.target.value })} className="border p-3 rounded-lg"><option value="">Select driver to mark attendance</option>{drivers.map((driver) => <option key={driver.driver_id} value={driver.driver_id}>{driver.name}</option>)}</select><select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })} className="border p-3 rounded-lg"><option>Present</option><option>Absent</option><option>Leave</option></select><input required type="datetime-local" value={form.check_in} onChange={(e) => setForm({ ...form, check_in: e.target.value })} className="border p-3 rounded-lg"/><input type="datetime-local" value={form.check_out} onChange={(e) => setForm({ ...form, check_out: e.target.value })} className="border p-3 rounded-lg"/><button className="bg-blue-600 text-white rounded-lg p-3">{editingId ? "Update Attendance" : "Mark Attendance"}</button></form><div className="bg-white mt-6 rounded-xl shadow p-6"><table className="w-full"><thead className="bg-gray-100"><tr><th className="p-3 text-left">Driver</th><th>Active Trip Vehicle ID</th><th>Check In</th><th>Check Out</th><th>Status</th><th>Actions</th></tr></thead><tbody>{visible.map((record) => <tr className="border-b text-center" key={record.attendance_id}><td className="p-3 text-left">{driverName(record.driver_id)}</td><td>{vehicleFor(record.driver_id)}</td><td>{new Date(record.check_in).toLocaleString()}</td><td>{record.check_out ? new Date(record.check_out).toLocaleString() : "Not checked out"}</td><td>{record.status}</td><td><button onClick={() => { setEditingId(record.attendance_id); setForm({ driver_id: record.driver_id, check_in: record.check_in.slice(0, 16), check_out: record.check_out?.slice(0, 16) || "", status: record.status }); }} className="bg-yellow-500 text-white px-3 py-1 rounded mr-2">Edit</button><button onClick={async () => { if (window.confirm("Delete this attendance record?")) { await api.delete(`/attendance/${record.attendance_id}`); await load(); } }} className="bg-red-600 text-white px-3 py-1 rounded">Delete</button></td></tr>)}{!visible.length && <tr><td colSpan="6" className="text-center p-6 text-gray-500">No attendance records yet.</td></tr>}</tbody></table></div></div>;
}
