import { useEffect, useMemo, useState } from "react";
import MapView from "../components/MapView";
import api from "../api/axios";

const active = (status) => status?.trim().toLowerCase() === "in progress";
export default function GPSTracking() {
  const [locations, setLocations] = useState([]); const [vehicles, setVehicles] = useState([]); const [drivers, setDrivers] = useState([]); const [trips, setTrips] = useState([]); const [form, setForm] = useState({ vehicle_id: "", latitude: "", longitude: "", speed: "" }); const [selectedVehicle, setSelectedVehicle] = useState(null); const [error, setError] = useState("");
  const load = async () => { try { const [gps, vehicleData, driverData, tripData] = await Promise.all([api.get("/gps/"), api.get("/vehicles/"), api.get("/drivers/"), api.get("/trips/")]); setLocations(gps.data); setVehicles(vehicleData.data); setDrivers(driverData.data); setTrips(tripData.data); } catch (e) { setError(e.response?.data?.detail || "Unable to load GPS locations."); } }; useEffect(() => { void load(); }, []);
  const activeTrips = useMemo(() => trips.filter((trip) => active(trip.status)), [trips]); const vehicleName = (id) => vehicles.find((item) => item.vehicle_id === id)?.registration_number || id; const driverName = (id) => drivers.find((item) => item.driver_id === id)?.name || "—";
  const mapVehicles = locations.filter((location) => activeTrips.some((trip) => trip.vehicle_id === location.vehicle_id)).map((location) => { const trip = activeTrips.find((item) => item.vehicle_id === location.vehicle_id); return { ...location, vehicle: vehicleName(location.vehicle_id), driver: driverName(trip.driver_id), location: `${Number(location.latitude).toFixed(6)}, ${Number(location.longitude).toFixed(6)}`, status: Number(location.speed) > 0 ? "Online" : "Offline", updated: new Date(location.timestamp).toLocaleString() }; });
  const save = async (event) => { event.preventDefault(); try { await api.post("/gps/", { ...form, latitude: Number(form.latitude), longitude: Number(form.longitude), speed: form.speed === "" ? null : Number(form.speed) }); setForm({ vehicle_id: "", latitude: "", longitude: "", speed: "" }); await load(); } catch (e) { setError(e.response?.data?.detail || "Unable to save GPS location."); } };
  return <div className="p-8 bg-gray-100 min-h-screen"><h1 className="text-4xl font-bold mb-2">GPS Tracking</h1><p className="text-gray-600 mb-6">Only vehicles on in-progress trips are shown. Coordinates below are their latest recorded GPS positions.</p>{error && <div className="mb-4 bg-red-50 text-red-700 rounded p-3">{error}</div>}<form onSubmit={save} className="bg-white rounded-xl shadow p-6 grid md:grid-cols-2 gap-4"><select required value={form.vehicle_id} onChange={(e) => setForm({ ...form, vehicle_id: e.target.value })} className="border rounded-lg p-3"><option value="">Select in-progress vehicle</option>{activeTrips.map((trip) => <option key={trip.trip_id} value={trip.vehicle_id}>{vehicleName(trip.vehicle_id)}</option>)}</select><input required type="number" step="any" placeholder="Latitude" value={form.latitude} onChange={(e) => setForm({ ...form, latitude: e.target.value })} className="border rounded-lg p-3"/><input required type="number" step="any" placeholder="Longitude" value={form.longitude} onChange={(e) => setForm({ ...form, longitude: e.target.value })} className="border rounded-lg p-3"/><input type="number" min="0" placeholder="Speed (km/h)" value={form.speed} onChange={(e) => setForm({ ...form, speed: e.target.value })} className="border rounded-lg p-3"/><button className="bg-blue-600 text-white rounded-lg p-3">Record GPS Location</button></form><div className="bg-white mt-6 rounded-xl shadow p-5"><MapView vehicles={mapVehicles} selectedVehicle={selectedVehicle} onSelectVehicle={setSelectedVehicle}/></div><div className="bg-white mt-6 rounded-xl shadow p-6"><table className="w-full"><thead className="bg-gray-100"><tr><th className="p-3 text-left">Vehicle</th><th>Driver</th><th>Exact coordinates</th><th>Speed</th><th>Updated</th></tr></thead><tbody>{mapVehicles.map((item) => <tr key={item.tracking_id} className="border-b text-center"><td className="p-3 text-left">{item.vehicle}</td><td>{item.driver}</td><td>{item.location}</td><td>{item.speed ?? 0} km/h</td><td>{item.updated}</td></tr>)}{!mapVehicles.length && <tr><td colSpan="5" className="p-6 text-center text-gray-500">No GPS locations for vehicles on in-progress trips.</td></tr>}</tbody></table></div></div>;
}
