import { useEffect, useMemo, useState } from "react";
import api from "../api/axios";
import MapView from "../components/MapView";

const emptyForm = { vehicle_id: "", driver_id: "", shipment_id: "", start_location: "", end_location: "", start_time: "", end_time: "", status: "Scheduled" };
const isActive = (status) => status?.trim().toLowerCase() === "in progress";

export default function Trips() {
  const [trips, setTrips] = useState([]); const [vehicles, setVehicles] = useState([]); const [drivers, setDrivers] = useState([]); const [shipments, setShipments] = useState([]);
  const [form, setForm] = useState(emptyForm); const [editingId, setEditingId] = useState(null); const [search, setSearch] = useState(""); const [error, setError] = useState("");
  const [route, setRoute] = useState(null); const [routeLoading, setRouteLoading] = useState(false);
  const load = async () => { try { const [tripData, vehicleData, driverData, shipmentData] = await Promise.all([api.get("/trips/"), api.get("/vehicles/"), api.get("/drivers/"), api.get("/shipments/")]); setTrips(tripData.data); setVehicles(vehicleData.data); setDrivers(driverData.data); setShipments(shipmentData.data); } catch (e) { setError(e.response?.data?.detail || "Unable to load trip records."); } };
  useEffect(() => { void load(); }, []);
  const name = (items, id, field) => items.find((item) => item[`${field}_id`] === id)?.[field === "vehicle" ? "registration_number" : field === "driver" ? "name" : "tracking_number"] || id;
  const visibleTrips = useMemo(() => trips.filter((trip) => `${name(vehicles, trip.vehicle_id, "vehicle")} ${name(drivers, trip.driver_id, "driver")} ${trip.start_location} ${trip.end_location}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => Number(isActive(b.status)) - Number(isActive(a.status))), [trips, vehicles, drivers, search]);
  const save = async (event) => { event.preventDefault(); try { const payload = { ...form, start_time: form.start_time ? new Date(form.start_time).toISOString() : null, end_time: form.end_time ? new Date(form.end_time).toISOString() : null }; if (editingId) await api.put(`/trips/${editingId}`, payload); else await api.post("/trips/", payload); setForm(emptyForm); setEditingId(null); await load(); } catch (e) { setError(e.response?.data?.detail || "Unable to save the trip."); } };
  const edit = (trip) => { setEditingId(trip.trip_id); setForm({ ...trip, start_time: trip.start_time?.slice(0, 16) || "", end_time: trip.end_time?.slice(0, 16) || "" }); };
  const showRoute = async (trip) => { try { setRouteLoading(true); setRoute(await api.get(`/trips/${trip.trip_id}/route`, { params: { route_type: "Fastest Route" } }).then((response) => ({ ...response.data, trip }))); } catch (e) { setError(e.response?.data?.detail || "Unable to calculate this route."); } finally { setRouteLoading(false); } };
  return <div className="p-8 bg-gray-100 min-h-screen"><h1 className="text-4xl font-bold mb-2">Trip Management</h1><p className="text-gray-600 mb-6">Live records used by the dashboard. In-progress trips appear first; completed trips remain below.</p>{error && <div className="mb-4 bg-red-50 text-red-700 p-3 rounded">{error}</div>}
    <form onSubmit={save} className="grid grid-cols-1 md:grid-cols-2 gap-4 bg-white rounded-xl shadow p-6"><select required value={form.vehicle_id} onChange={(e) => setForm({ ...form, vehicle_id: e.target.value })} className="border rounded-lg p-3"><option value="">Select vehicle</option>{vehicles.map((v) => <option key={v.vehicle_id} value={v.vehicle_id}>{v.registration_number}</option>)}</select><select required value={form.driver_id} onChange={(e) => setForm({ ...form, driver_id: e.target.value })} className="border rounded-lg p-3"><option value="">Select driver</option>{drivers.map((d) => <option key={d.driver_id} value={d.driver_id}>{d.name}</option>)}</select><select required value={form.shipment_id} onChange={(e) => setForm({ ...form, shipment_id: e.target.value })} className="border rounded-lg p-3"><option value="">Select shipment</option>{shipments.map((s) => <option key={s.shipment_id} value={s.shipment_id}>{s.tracking_number}</option>)}</select><select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })} className="border rounded-lg p-3"><option>Scheduled</option><option>In Progress</option><option>Completed</option></select><input required placeholder="Start location" value={form.start_location} onChange={(e) => setForm({ ...form, start_location: e.target.value })} className="border rounded-lg p-3"/><input required placeholder="End location" value={form.end_location} onChange={(e) => setForm({ ...form, end_location: e.target.value })} className="border rounded-lg p-3"/><input type="datetime-local" value={form.start_time} onChange={(e) => setForm({ ...form, start_time: e.target.value })} className="border rounded-lg p-3"/><input type="datetime-local" value={form.end_time} onChange={(e) => setForm({ ...form, end_time: e.target.value })} className="border rounded-lg p-3"/><div className="flex gap-3"><button className="bg-blue-600 text-white px-5 py-3 rounded-lg">{editingId ? "Update Trip" : "Add Trip"}</button>{editingId && <button type="button" onClick={() => { setForm(emptyForm); setEditingId(null); }} className="bg-gray-200 px-5 rounded-lg">Cancel</button>}</div></form>
    {route && <div className="mt-6 bg-white rounded-xl shadow p-6"><div className="flex justify-between items-start mb-4"><div><h2 className="text-xl font-bold">{route.trip.start_location} → {route.trip.end_location}</h2><p className="text-gray-600">{route.distance_km} km · {route.duration_minutes} minutes · ETA {new Date(route.eta).toLocaleString()}</p>{route.fallback && <p className="text-amber-700 text-sm mt-1">Showing an estimated straight-line route because OSRM was unavailable.</p>}</div><button onClick={() => setRoute(null)} className="text-gray-600">Close</button></div><div className="grid md:grid-cols-2 gap-4 mb-4"><div className={`rounded-lg p-4 ${route.traffic_level === "High" ? "bg-red-50 text-red-800" : route.traffic_level === "Moderate" ? "bg-amber-50 text-amber-800" : "bg-green-50 text-green-800"}`}><p className="font-semibold">Traffic estimate: {route.traffic_level}</p><p className="text-sm">Estimated delay: {route.traffic_delay_minutes} min · adjusted duration: {route.adjusted_duration_minutes} min</p></div><div className="rounded-lg p-4 bg-slate-50 text-slate-800"><p className="font-semibold">Estimated toll gates: {route.toll_gates_estimate}</p><p className="text-sm">Planning estimate based on route distance; verify actual tolls before dispatch.</p></div></div><MapView routeGeometry={route.geometry} /></div>}
    <div className="mt-6 bg-white rounded-xl shadow p-6"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search trips" className="border rounded-lg p-3 w-full mb-4"/><div className="overflow-x-auto"><table className="w-full"><thead className="bg-gray-100"><tr><th className="p-3 text-left">Vehicle</th><th>Driver</th><th>Route</th><th>Status</th><th>Actions</th></tr></thead><tbody>{visibleTrips.map((trip) => <tr className="border-b text-center" key={trip.trip_id}><td className="p-3 text-left">{name(vehicles, trip.vehicle_id, "vehicle")}</td><td>{name(drivers, trip.driver_id, "driver")}</td><td>{trip.start_location} → {trip.end_location}</td><td>{trip.status}</td><td><button onClick={() => showRoute(trip)} disabled={routeLoading} className="bg-blue-600 text-white px-3 py-1 rounded mr-2">{routeLoading ? "Loading…" : "Show Route"}</button><button onClick={() => edit(trip)} className="bg-yellow-500 text-white px-3 py-1 rounded mr-2">Edit</button><button onClick={async () => { if (window.confirm("Delete this trip?")) { await api.delete(`/trips/${trip.trip_id}`); await load(); } }} className="bg-red-600 text-white px-3 py-1 rounded">Delete</button></td></tr>)}{!visibleTrips.length && <tr><td colSpan="5" className="p-6 text-center text-gray-500">No trips found.</td></tr>}</tbody></table></div></div></div>;
}
